version: '3.8'

networks:
  traefik:
    external: true

services:
  morphy-frontend:
    image: ambro66/morphy-frontend:latest
    container_name: morphy-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.morphy.rule=Host(`formipeek.com`)
      - traefik.http.routers.morphy.entrypoints=web
      - traefik.http.middlewares.morphy-redirect.redirectscheme.scheme=https
      - traefik.http.routers.morphy.middlewares=morphy-redirect
      - traefik.http.routers.morphy-secure.rule=Host(`formipeek.com`)
      - traefik.http.routers.morphy-secure.entrypoints=websecure
      - traefik.http.routers.morphy-secure.tls=true
      - traefik.http.routers.morphy-secure.tls.certresolver=letsencrypt
      - traefik.http.services.morphy.loadbalancer.server.port=3000
